name: Synchronisation avec le repository principal
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v2
    - name: Run Deployment Script
      run: |
        git remote add upstream https://github.com/DSsenegal/sandiara-market.git
        git fetch upstream
        git checkout feat/synchronize
        git merge upstream/feat/synchronize
        git push origin feat/synchronize
