name: Update Fork
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Add the upstream repository
        run: |
          git remote add upstream https://github.com/DSsenegal/sandiara-market.git
          git fetch upstream
      - name: Merge upstream changes
        run: |
          git config --global user.email "papamatardiop3@gmail.com"
          git config --global user.name "zlorg"
          git remote set-url origin https://zlorgoncho1:${{ secrets.PAT }}@github.com/zlorgoncho1/sandiara-market.git
          git checkout main
          git merge upstream/main --allow-unrelated-histories
      - name: Push changes to the forked repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git push origin main
